In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/MaxWarriner/Data-Mining/refs/heads/main/imdb_top_1000.csv")
df = df.fillna(0)
df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,0
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,0
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,0,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,0
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,0,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,0

In [4]:
df = df[['Series_Title', 'IMDB_Rating', 'Meta_score', 'Gross', 'Certificate', 'Runtime']]
df['Runtime'] = df['Runtime'].str.replace('min', '')
df['Gross'] = df['Gross'].str.replace(',', '')
df['Gross'] = df['Gross'].astype(float)
df

/tmp/ipykernel_3864/1986157891.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Runtime'] = df['Runtime'].str.replace('min', '')
/tmp/ipykernel_3864/1986157891.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gross'] = df['Gross'].str.replace(',', '')
/tmp/ipykernel_3864/1986157891.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gross'] = df['Gross'].astype(float)

,Series_Title,IMDB_Rating,Meta_score,Gross,Certificate,Runtime
0,The Shawshank Redemption,9.3,80.0,28341469.0,A,142
1,The Godfather,9.2,100.0,134966411.0,A,175
2,The Dark Knight,9.0,84.0,534858444.0,UA,152
3,The Godfather: Part II,9.0,90.0,57300000.0,A,202
4,12 Angry Men,9.0,96.0,4360000.0,U,96
...,...,...,...,...,...,...
995,Breakfast at Tiffany's,7.6,76.0,NaN,A,115
996,Giant,7.6,84.0,NaN,G,201
997,From Here to Eternity,7.6,85.0,30500000.0,Passed,118
998,Lifeboat,7.6,78.0,NaN,0,97
999,The 39 Steps,7.6,93.0,NaN,0,86

In [ ]:
df['Runtime'] = df['Runtime'].astype(float)

/tmp/ipython-input-4034414702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Runtime'] = df['Runtime'].astype(float)

In [5]:
dummies = pd.get_dummies(df['Certificate'])
df = pd.concat([df, dummies], axis=1)

In [6]:
df = df[['Series_Title', 'IMDB_Rating','Meta_score', 'Gross', 'Runtime', 'PG-13', 'R']]

In [7]:
df

,Series_Title,IMDB_Rating,Meta_score,Gross,Runtime,PG-13,R
0,The Shawshank Redemption,9.3,80.0,28341469.0,142,False,False
1,The Godfather,9.2,100.0,134966411.0,175,False,False
2,The Dark Knight,9.0,84.0,534858444.0,152,False,False
3,The Godfather: Part II,9.0,90.0,57300000.0,202,False,False
4,12 Angry Men,9.0,96.0,4360000.0,96,False,False
...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,7.6,76.0,NaN,115,False,False
996,Giant,7.6,84.0,NaN,201,False,False
997,From Here to Eternity,7.6,85.0,30500000.0,118,False,False
998,Lifeboat,7.6,78.0,NaN,97,False,False
999,The 39 Steps,7.6,93.0,NaN,86,False,False

In [8]:
df['PG-13'] = df['PG-13'].replace({True: 1, False: 0})
df

/tmp/ipykernel_3864/3761119252.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['PG-13'] = df['PG-13'].replace({True: 1, False: 0})

,Series_Title,IMDB_Rating,Meta_score,Gross,Runtime,PG-13,R
0,The Shawshank Redemption,9.3,80.0,28341469.0,142,0,False
1,The Godfather,9.2,100.0,134966411.0,175,0,False
2,The Dark Knight,9.0,84.0,534858444.0,152,0,False
3,The Godfather: Part II,9.0,90.0,57300000.0,202,0,False
4,12 Angry Men,9.0,96.0,4360000.0,96,0,False
...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,7.6,76.0,NaN,115,0,False
996,Giant,7.6,84.0,NaN,201,0,False
997,From Here to Eternity,7.6,85.0,30500000.0,118,0,False
998,Lifeboat,7.6,78.0,NaN,97,0,False
999,The 39 Steps,7.6,93.0,NaN,86,0,False

In [9]:
df['R'] = df['R'].replace({True: 1, False: 0})
df

/tmp/ipykernel_3864/2937526039.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['R'] = df['R'].replace({True: 1, False: 0})

,Series_Title,IMDB_Rating,Meta_score,Gross,Runtime,PG-13,R
0,The Shawshank Redemption,9.3,80.0,28341469.0,142,0,0
1,The Godfather,9.2,100.0,134966411.0,175,0,0
2,The Dark Knight,9.0,84.0,534858444.0,152,0,0
3,The Godfather: Part II,9.0,90.0,57300000.0,202,0,0
4,12 Angry Men,9.0,96.0,4360000.0,96,0,0
...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,7.6,76.0,NaN,115,0,0
996,Giant,7.6,84.0,NaN,201,0,0
997,From Here to Eternity,7.6,85.0,30500000.0,118,0,0
998,Lifeboat,7.6,78.0,NaN,97,0,0
999,The 39 Steps,7.6,93.0,NaN,86,0,0

In [ ]:
from sklearn import preprocessing
import numpy as np

In [ ]:
scalingObj = preprocessing.MinMaxScaler()
new_df = scalingObj.fit_transform(df[['IMDB_Rating', 'Meta_score', 'Gross', 'Runtime', 'PG-13', 'R']])
new_df

array([[1.        , 0.8       , 0.03025659, 0.35144928, 0.        ,
        0.        ],
       [0.94117647, 1.        , 0.14409174, 0.47101449, 0.        ,
        0.        ],
       [0.82352941, 0.84      , 0.57102536, 0.38768116, 0.        ,
        0.        ],
       ...,
       [0.        , 0.85      , 0.03256108, 0.26449275, 0.        ,
        0.        ],
       [0.        , 0.78      ,        nan, 0.1884058 , 0.        ,
        0.        ],
       [0.        , 0.93      ,        nan, 0.14855072, 0.        ,
        0.        ]])

In [10]:
def min_finder(new_point, df):
  new_point_scaled = scalingObj.transform(new_point)
  df_diff = new_df - new_point_scaled
  df_diff = abs(df_diff)
  distances = df_diff.sum(axis=1).sort_values()
  print(distances.head(1).index)

In [11]:
new_movie = np.array([[5.3, 72, 10000000,120,0,1]])
new_point_scaled = scalingObj.transform(new_movie)
df_diff = new_df - new_point_scaled
df_diff = abs(df_diff)
distances = df_diff.sum(axis=1)
distances
#min_finder(new_point=new_movie, df = new_df)

NameError: name 'np' is not defined